name: Workshop CI Mentoria
#[script de pipeline] YAML
# [gatilhos] (manual, agendada, quando houver mudanças, etc.)

on:
  workflow_dispatch: 

jobs:
  tests:
    # [config do sistema operacional] (mac/windows/linux/etc)
    runs-on: ubuntu-latest 
    # [variaveis] (de ambiente, chaves de acesso)
    env:
      API_BASE_URL: 'http://localhost:3000'
      PORT: 4000
    # [projetos] (aplicacoes FE/BE, apps, projetos de testes, etc)
    steps:
      - name: Clone do projeto
        uses: actions/checkout@v6.1.0  
      
      - name: Instalando deps do projeto
        run: npm install

      - name: Iniciando servidor de mock
        run: npm run mock-server &

      - name: Iniciando servidor da aplicacao
        run: npm run server

      - name: Executando os testes e2e do projeto
        run: npx cypress run
