name: Workshop CI Mentoria

#[script de pipeline] YAML
# [gatilhos] (manual, agendada, quando houver mudanças, etc.)

on:
  workflow_dispatch: 

jobs:
  tests:

# [config do sistema operacional] (mac/windows/linux/etc)
  runs-on: ubuntu-latest 
# [variaveis] (de ambiente, chaves de acesso)
    env:
      API_BASE_URL: 'http://localhost:3000'
      PORT: 4000  # URL base da API REST Banco API ou do Mock Server
    steps:
# [projetos] (aplicacoes FE/BE, apps, projetos de testes, etc)
      - name: Clone do projeto
        uses: actions/checkout@v6.1.0  
# [dependencias do projeto] (node/npm, java/maven, python/pip)
      - name: Instalando deps do proejto
        run: npm install
# [acoes para verificar regras/políticas] (cobertura de código, formatacao, testes ui/e2e/unit/etc.)
      - name: Iniciando servidor de mock
        run: npm run mock-server &
      - name: Iniciando servidor da aplicacao
        run: npm run server
      - name: Executando os testes e2e do projeto
        run: npx cypress run
